apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: web
      image: fabricioveronez/web-page:blue
      ports:
        - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod0
  labels:
    app: green
spec:
  containers:
    - name: web
      image: fabricioveronez/web-page:green
      ports:
        - containerPort: 80